[package]
name = "assemble"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
toml = "0.5"

[package.metadata.dist]
dist = false
